version: '3'

services:
  elasticsearch:
    container_name: docker-elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:6.6.0
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    volumes:
      - es-data:/usr/share/elasticsearch/data
    networks:
      - es-net
    ports:
      - 9200:9200
    healthcheck:
      test: curl -s -f http://docker-elasticsearch:9200/_cat/health >/dev/null || exit 1
      interval: 30s
      timeout: 10s
      retries: 5

  kibana:
    container_name: docker-kibana
    image: docker.elastic.co/kibana/kibana:6.6.0
    environment:
      - ELASTICSEARCH_HOSTS=http://docker-elasticsearch:9200
    networks:
      - es-net
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601
    healthcheck:
      test: curl -s -I http://docker-kibana:5601 | grep -q 'HTTP/1.1 302 Found' >/dev/null || exit 1
      interval: 30s
      timeout: 10s
      retries: 5
      
  filebeat:
    user: root
    container_name: docker-filebeat
    image: docker.elastic.co/beats/filebeat:6.6.0
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./filebeat.yml:/usr/share/filebeat/filebeat.yml
      - ./logs:/var/log/app
    depends_on:
      - elasticsearch
    command: ["--strict.perms=false"]
    networks:
      - es-net
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "50"

networks:
  es-net:
    driver: bridge

volumes:
  es-data:
    driver: local
